<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'ZendCartCookie\Module'                                   => __DIR__ . '/Module.php',
  'ZendCartCookie\Adapter\CartCookieAdapterInterface'       => __DIR__ . '/src/ZendCartCookie/Adapter/CartCookieAdapterInterface.php',
  'ZendCartCookie\Adapter\DoctrineCartCookieAdapter'        => __DIR__ . '/src/ZendCartCookie/Adapter/DoctrineCartCookieAdapter.php',
  'ZendCartCookie\Entity\CartCookie'                        => __DIR__ . '/src/ZendCartCookie/Entity/CartCookie.php',
  'ZendCartCookie\Entity\CartCookieEntityInterface'         => __DIR__ . '/src/ZendCartCookie/Entity/CartCookieEntityInterface.php',
  'ZendCartCookie\Service\CartCookie'                       => __DIR__ . '/src/ZendCartCookie/Service/CartCookie.php',
  'ZendCartCookie\Service\Factory\CartCookieServiceFactory' => __DIR__ . '/src/ZendCartCookie/Service/Factory/CartCookieServiceFactory.php',
);
